/*                name , handler */
INTERRUPT_HANDLER(reset, reset_interrupt)
INTERRUPT_HANDLER(undefined, reserved_interrupt)
INTERRUPT_HANDLER(svcall, svcall_interrupt)
INTERRUPT_HANDLER(prefetch, timer_interrupt)
INTERRUPT_HANDLER(abort, timer_interrupt)
INTERRUPT_HANDLER(uart, timer_interrupt)
INTERRUPT_HANDLER(timer0, timer_interrupt)
INTERRUPT_HANDLER(timer1, timer_interrupt)
INTERRUPT_HANDLER(timer2, timer_interrupt)
INTERRUPT_HANDLER(timer3, timer_interrupt)
INTERRUPT_HANDLER(timer5, timer_interrupt)
INTERRUPT_HANDLER(timer6, timer_interrupt)
INTERRUPT_HANDLER(timer7, timer_interrupt)
